"""empty message

Revision ID: 4503af5b670f
Revises: aa832b5cf441
Create Date: 2021-01-07 14:08:08.331259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4503af5b670f'
down_revision = 'aa832b5cf441'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bought_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('food_pantry', sa.String(length=120), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bought_item_food_pantry'), 'bought_item', ['food_pantry'], unique=False)
    op.create_index(op.f('ix_bought_item_name'), 'bought_item', ['name'], unique=False)
    op.create_index(op.f('ix_bought_item_price'), 'bought_item', ['price'], unique=False)
    op.create_index(op.f('ix_bought_item_quantity'), 'bought_item', ['quantity'], unique=False)
    op.add_column('store', sa.Column('store_type', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_store_store_type'), 'store', ['store_type'], unique=False)
    op.drop_index('ix_store_storeType', table_name='store')
    op.drop_column('store', 'storeType')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store', sa.Column('storeType', sa.VARCHAR(length=64), nullable=True))
    op.create_index('ix_store_storeType', 'store', ['storeType'], unique=False)
    op.drop_index(op.f('ix_store_store_type'), table_name='store')
    op.drop_column('store', 'store_type')
    op.drop_index(op.f('ix_bought_item_quantity'), table_name='bought_item')
    op.drop_index(op.f('ix_bought_item_price'), table_name='bought_item')
    op.drop_index(op.f('ix_bought_item_name'), table_name='bought_item')
    op.drop_index(op.f('ix_bought_item_food_pantry'), table_name='bought_item')
    op.drop_table('bought_item')
    # ### end Alembic commands ###
